package perfharness

import (
	"bufio"
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"time"
)

type rrKind struct {
	name   string
	weight int
}

var rrMix = []rrKind{
	{"A", 50}, {"AAAA", 15}, {"CNAME", 15}, {"TXT", 10}, {"SRV", 5}, {"MX", 5},
}

var ttls = []int{300, 600, 900, 1800, 3600}

// ZoneGenResult describes a generated zone file.
type ZoneGenResult struct {
	Zone    string
	Records int
	Seed    int
	Path    string
	Elapsed time.Duration
	Bytes   int
}

// GenerateZone streams a deterministic zone file. The RNG is Go's, so the
// bytes differ from the old Python generator; the type mix and layout match.
func GenerateZone(zone string, records, seed int, output string) (ZoneGenResult, error) {
	if records < 1 {
		return ZoneGenResult{}, fmt.Errorf("records must be >= 1")
	}
	zone = trimDot(zone)
	path := output
	if path == "" {
		var err error
		path, err = defaultZonePath(zone)
		if err != nil {
			return ZoneGenResult{}, err
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return ZoneGenResult{}, err
	}
	f, err := os.Create(path)
	if err != nil {
		return ZoneGenResult{}, err
	}
	defer func() { _ = f.Close() }()
	bw := bufio.NewWriterSize(f, 1<<20)
	started := time.Now()
	n, err := writeZone(bw, zone, records, seed)
	if err != nil {
		return ZoneGenResult{}, err
	}
	if err := bw.Flush(); err != nil {
		return ZoneGenResult{}, err
	}
	return ZoneGenResult{
		Zone: zone, Records: records, Seed: seed, Path: path,
		Elapsed: time.Since(started), Bytes: n,
	}, nil
}

func writeZone(w *bufio.Writer, zone string, records, seed int) (int, error) {
	width := len(fmt.Sprintf("%d", records))
	if width < 7 {
		width = 7
	}
	var written int
	line := func(s string) error {
		n, err := w.WriteString(s)
		written += n
		if err != nil {
			return err
		}
		err = w.WriteByte('\n')
		written++
		return err
	}
	header := []string{
		fmt.Sprintf("; Zone file for %s", zone),
		"; Generated by dns-perf zonegen",
		"",
		fmt.Sprintf("$ORIGIN %s.", zone),
		"$TTL 3600",
		"",
		"; SOA record",
		fmt.Sprintf("@\tIN\tSOA\tns1.%s. admin.%s. (", zone, zone),
		"\t\t1\t\t\t; Serial",
		"\t\t3600\t\t; refresh",
		"\t\t600\t\t; retry",
		"\t\t86400\t\t; expire",
		"\t\t300\t\t; minimum TTL",
		"\t)",
		"",
		"; NS records",
		fmt.Sprintf("@\tIN\tNS\tns1.%s.", zone),
		fmt.Sprintf("@\tIN\tNS\tns2.%s.", zone),
		"",
		"; NS host records",
		"ns1\tIN\tA\t172.28.0.10",
		"ns2\tIN\tA\t172.28.0.11",
		"",
		"; Mail servers (targets for MX records)",
	}
	for _, h := range header {
		if err := line(h); err != nil {
			return written, err
		}
	}
	for i := 1; i <= 5; i++ {
		if err := line(fmt.Sprintf("mail%d\tIN\tA\t172.28.1.%d", i, i)); err != nil {
			return written, err
		}
	}
	if err := line(""); err != nil {
		return written, err
	}
	if err := line("; Service servers (targets for SRV records)"); err != nil {
		return written, err
	}
	for i := 1; i <= 20; i++ {
		if err := line(fmt.Sprintf("server%d\tIN\tA\t172.28.2.%d", i, i)); err != nil {
			return written, err
		}
	}
	if err := line(""); err != nil {
		return written, err
	}
	if err := line("; CNAME targets"); err != nil {
		return written, err
	}
	for i := 1; i <= 100; i++ {
		if err := line(fmt.Sprintf("target%d\tIN\tA\t172.28.3.%d", i, i)); err != nil {
			return written, err
		}
	}
	for _, h := range []string{"", "; ========================================", fmt.Sprintf("; %d generated records below", records), "; ========================================", ""} {
		if err := line(h); err != nil {
			return written, err
		}
	}
	rng := rand.New(rand.NewSource(int64(seed)))
	total := 0
	for _, k := range rrMix {
		total += k.weight
	}
	for i := 1; i <= records; i++ {
		if err := line(recordLine(rng, zone, i, width, pickKind(rng, total))); err != nil {
			return written, err
		}
	}
	return written, nil
}

func pickKind(rng *rand.Rand, total int) string {
	n := rng.Intn(total)
	acc := 0
	for _, k := range rrMix {
		acc += k.weight
		if n < acc {
			return k.name
		}
	}
	return "A"
}

func recordLine(rng *rand.Rand, zone string, index, width int, kind string) string {
	host := fmt.Sprintf("host%0*d", width, index)
	ttl := ttls[rng.Intn(len(ttls))]
	switch kind {
	case "A":
		return fmt.Sprintf("%s\t%d\tIN\tA\t%d.%d.%d.%d", host, ttl, rng.Intn(241)+10, rng.Intn(256), rng.Intn(256), rng.Intn(254)+1)
	case "AAAA":
		return fmt.Sprintf("%s\t%d\tIN\tAAAA\t%04x:%04x:%04x:%04x:%04x:%04x:%04x:%04x", host, ttl,
			rng.Intn(0x10000), rng.Intn(0x10000), rng.Intn(0x10000), rng.Intn(0x10000),
			rng.Intn(0x10000), rng.Intn(0x10000), rng.Intn(0x10000), rng.Intn(0x10000))
	case "CNAME":
		return fmt.Sprintf("%s\t%d\tIN\tCNAME\ttarget%d.%s.", host, ttl, rng.Intn(100)+1, zone)
	case "TXT":
		return fmt.Sprintf("%s\t%d\tIN\tTXT\t\"Record %d - Generated test data for pagination testing\"", host, ttl, index)
	case "MX":
		prio := []int{10, 20, 30}[rng.Intn(3)]
		return fmt.Sprintf("%s\t%d\tIN\tMX\t%d mail%d.%s.", host, ttl, prio, rng.Intn(5)+1, zone)
	default:
		port := []int{80, 443, 8080, 8443}[rng.Intn(4)]
		return fmt.Sprintf("_http._tcp.%s\t%d\tIN\tSRV\t%d %d %d server%d.%s.", host, ttl, rng.Intn(10)+1, rng.Intn(50)+1, port, rng.Intn(20)+1, zone)
	}
}

func defaultZonePath(zone string) (string, error) {
	name := "db." + trimDot(zone)
	if writableDir("/perf-zones") {
		return filepath.Join("/perf-zones", name), nil
	}
	dir := filepath.Join(".tmp", "perf")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	return filepath.Join(dir, name), nil
}

func writableDir(dir string) bool {
	fi, err := os.Stat(dir)
	if err != nil || !fi.IsDir() {
		return false
	}
	probe := filepath.Join(dir, ".write-probe")
	if err := os.WriteFile(probe, []byte("ok"), 0o644); err != nil {
		return false
	}
	_ = os.Remove(probe)
	return true
}
