"""Streaming deterministic DNS zone file generator.

Produces zone files with a fixed type mix similar to
``examples/bind/zones/db.largezone.test`` (A/AAAA/CNAME/TXT/MX/SRV). Names are
zero-padded ``hostNNNNNNN`` so cursor pagination is deterministic.

Constant memory: records are written one line at a time; nothing is buffered
beyond a small write buffer.
"""

from __future__ import annotations

import argparse
import random
import sys
import time
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import TextIO

# Approximate mix from db.largezone.test (~50k): A 50%, AAAA 15%, CNAME 15%,
# TXT 10%, SRV 5%, MX 5%.
TYPE_WEIGHTS: list[tuple[str, int]] = [
    ("A", 50),
    ("AAAA", 15),
    ("CNAME", 15),
    ("TXT", 10),
    ("SRV", 5),
    ("MX", 5),
]

TTLS = (300, 600, 900, 1800, 3600)

PRESETS: dict[str, int] = {
    "100k": 100_000,
    "1m": 1_000_000,
    "5m": 5_000_000,
}

DEFAULT_ZONE = "perf5m.test"
DEFAULT_SEED = 42
DEFAULT_OUTPUT_DIR = Path("/perf-zones")
FALLBACK_OUTPUT_DIR = Path(".tmp/perf")


@dataclass(frozen=True)
class ZoneGenResult:
    """Metadata about a generated zone file."""

    zone: str
    records: int
    seed: int
    path: Path
    elapsed_seconds: float
    bytes_written: int


def _type_choices() -> tuple[list[str], list[int]]:
    types = [t for t, _ in TYPE_WEIGHTS]
    weights = [w for _, w in TYPE_WEIGHTS]
    return types, weights


def _host_width(records: int) -> int:
    return max(7, len(str(records)))


def _infra_lines(zone: str) -> Iterator[str]:
    """Emit SOA, NS, and shared target A records used by MX/SRV/CNAME."""
    yield f"; Zone file for {zone}"
    yield "; Generated by perf.zonegen (deterministic)"
    yield ""
    yield f"$ORIGIN {zone}."
    yield "$TTL 3600"
    yield ""
    yield "; SOA record"
    yield f"@\tIN\tSOA\tns1.{zone}. admin.{zone}. ("
    yield "\t\t1\t\t\t; Serial"
    yield "\t\t3600\t\t; refresh"
    yield "\t\t600\t\t; retry"
    yield "\t\t86400\t\t; expire"
    yield "\t\t300\t\t; minimum TTL"
    yield "\t)"
    yield ""
    yield "; NS records"
    yield f"@\tIN\tNS\tns1.{zone}."
    yield f"@\tIN\tNS\tns2.{zone}."
    yield ""
    yield "; NS host records"
    yield "ns1\tIN\tA\t172.28.0.10"
    yield "ns2\tIN\tA\t172.28.0.11"
    yield ""
    yield "; Mail servers (targets for MX records)"
    for i in range(1, 6):
        yield f"mail{i}\tIN\tA\t172.28.1.{i}"
    yield ""
    yield "; Service servers (targets for SRV records)"
    for i in range(1, 21):
        yield f"server{i}\tIN\tA\t172.28.2.{i}"
    yield ""
    yield "; CNAME targets"
    for i in range(1, 101):
        yield f"target{i}\tIN\tA\t172.28.3.{i}"
    yield ""
    yield "; ========================================"
    yield "; GENERATED_RECORDS_BELOW"
    yield "; ========================================"
    yield ""


def _record_line(
    rng: random.Random,
    zone: str,
    index: int,
    width: int,
    rdtype: str,
) -> str:
    host = f"host{index:0{width}d}"
    ttl = rng.choice(TTLS)
    if rdtype == "A":
        a, b, c = rng.randint(10, 250), rng.randint(0, 255), rng.randint(0, 255)
        d = rng.randint(1, 254)
        return f"{host}\t{ttl}\tIN\tA\t{a}.{b}.{c}.{d}"
    if rdtype == "AAAA":
        hextets = ":".join(f"{rng.randint(0, 0xFFFF):04x}" for _ in range(8))
        return f"{host}\t{ttl}\tIN\tAAAA\t{hextets}"
    if rdtype == "CNAME":
        target = rng.randint(1, 100)
        return f"{host}\t{ttl}\tIN\tCNAME\ttarget{target}.{zone}."
    if rdtype == "TXT":
        return (
            f'{host}\t{ttl}\tIN\tTXT\t"Record {index} - Generated test data for pagination testing"'
        )
    if rdtype == "MX":
        prio = rng.choice((10, 20, 30))
        mail = rng.randint(1, 5)
        return f"{host}\t{ttl}\tIN\tMX\t{prio} mail{mail}.{zone}."
    if rdtype == "SRV":
        pri, weight = rng.randint(1, 10), rng.randint(1, 50)
        port = rng.choice((80, 443, 8080, 8443))
        server = rng.randint(1, 20)
        return f"_http._tcp.{host}\t{ttl}\tIN\tSRV\t{pri} {weight} {port} server{server}.{zone}."
    raise ValueError(f"unsupported rdtype: {rdtype}")


def iter_zone_lines(
    zone: str,
    records: int,
    seed: int = DEFAULT_SEED,
) -> Iterator[str]:
    """Yield zone-file lines (header + ``records`` generated RRs)."""
    if records < 1:
        raise ValueError("records must be >= 1")
    zone = zone.rstrip(".")
    width = _host_width(records)
    for line in _infra_lines(zone):
        if line == "; GENERATED_RECORDS_BELOW":
            yield f"; {records} generated records below"
        else:
            yield line

    rng = random.Random(seed)
    types, weights = _type_choices()
    for i in range(1, records + 1):
        rdtype = rng.choices(types, weights=weights, k=1)[0]
        yield _record_line(rng, zone, i, width, rdtype)


def default_output_path(zone: str, output_dir: Path | None = None) -> Path:
    """Resolve output path, preferring ``/perf-zones`` when writable."""
    zone = zone.rstrip(".")
    filename = f"db.{zone}"
    if output_dir is not None:
        return output_dir / filename
    preferred = DEFAULT_OUTPUT_DIR
    if preferred.is_dir() and preferred.exists():
        try:
            # Probe writability without leaving debris.
            probe = preferred / ".write-probe"
            probe.write_text("ok", encoding="utf-8")
            probe.unlink(missing_ok=True)
            return preferred / filename
        except OSError:
            pass
    FALLBACK_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    return FALLBACK_OUTPUT_DIR / filename


def generate_zone(
    zone: str = DEFAULT_ZONE,
    records: int = PRESETS["5m"],
    seed: int = DEFAULT_SEED,
    output: Path | None = None,
    file: TextIO | None = None,
) -> ZoneGenResult:
    """Write a zone file; return metadata. Streams line-by-line."""
    zone = zone.rstrip(".")
    path = output or default_output_path(zone)
    path.parent.mkdir(parents=True, exist_ok=True)

    started = time.perf_counter()
    bytes_written = 0
    close_after = False
    out = file
    if out is None:
        out = path.open("w", encoding="utf-8", buffering=1024 * 1024)
        close_after = True
    try:
        for line in iter_zone_lines(zone, records, seed):
            data = line + "\n"
            out.write(data)
            bytes_written += len(data.encode("utf-8"))
        out.flush()
    finally:
        if close_after and out is not None:
            out.close()

    elapsed = time.perf_counter() - started
    return ZoneGenResult(
        zone=zone,
        records=records,
        seed=seed,
        path=path,
        elapsed_seconds=elapsed,
        bytes_written=bytes_written,
    )


def resolve_record_count(preset: str | None, records: int | None) -> int:
    if preset is not None:
        key = preset.lower()
        if key not in PRESETS:
            raise ValueError(f"unknown preset {preset!r}; choose from {sorted(PRESETS)}")
        return PRESETS[key]
    if records is not None:
        return records
    return PRESETS["5m"]


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate a deterministic large DNS zone file")
    parser.add_argument("--zone", default=DEFAULT_ZONE, help="Zone apex (default: %(default)s)")
    parser.add_argument(
        "--records",
        type=int,
        default=None,
        help="Number of generated records (default: 5_000_000)",
    )
    parser.add_argument(
        "--preset",
        choices=sorted(PRESETS),
        default=None,
        help="Named size preset (overrides --records)",
    )
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help="PRNG seed")
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path (default: /perf-zones/db.<zone> or .tmp/perf/)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    count = resolve_record_count(args.preset, args.records)
    result = generate_zone(
        zone=args.zone,
        records=count,
        seed=args.seed,
        output=args.output,
    )
    print(
        f"Wrote {result.records} records for {result.zone}. "
        f"path={result.path} bytes={result.bytes_written} "
        f"elapsed={result.elapsed_seconds:.2f}s seed={result.seed}",
        file=sys.stderr,
    )
    print(result.path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
